services:
  nextjs:
    build: https://github.com/Dev-NETI/CALLING_CARD_FRONTEND.git
    container_name: business-card
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
